
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-07
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-javadoc","number":77,"title":"Fix javadoc issues for RecommendationRequest","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/77"},{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"nw-admin-page","number":68,"title":"Admin recommendation requests page frontend and tests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/68"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"req-type-edit-page","number":67,"title":"LD - Edit page for Request Types","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/67"}]
