
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-07
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-07
pull_requests: [{"author":{"id":"U_kgDOCL-Znw","is_bot":false,"login":"divyagsubramonian","name":"Divya Subramonian"},"headRefName":"rr-backend","number":73,"title":"DS - Updated RR entity, repository, and database migration files","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/73"},{"author":{"id":"U_kgDOB3EPsA","is_bot":false,"login":"kanav9063","name":""},"headRefName":"ka-new-fixtures","number":71,"title":"Update fixtures for recommendation requests based on changes in entity file","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/71"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-home-page","number":69,"title":"Update home page style and text","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/69"},{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"nw-admin-page","number":68,"title":"Admin recommendation requests page frontend and tests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/68"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"req-type-edit-page","number":67,"title":"LD - Edit page for Request Types","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/67"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"req-type-create-page","number":63,"title":"LD - Create Page for RequestType","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/63"},{"author":{"id":"U_kgDOB3EPsA","is_bot":false,"login":"kanav9063","name":""},"headRefName":"ka-form-rr","number":61,"title":"Form Component for RecommendationRequest plus tests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/61"},{"author":{"id":"U_kgDOCL-Znw","is_bot":false,"login":"divyagsubramonian","name":"Divya Subramonian"},"headRefName":"ds-rr-controller","number":59,"title":"ds - updated rr controller and tests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/59"},{"author":{"id":"U_kgDOBo-IIw","is_bot":false,"login":"eug-wong","name":"Eugene Wong"},"headRefName":"ew-remove-restaurants","number":54,"title":"EW - Remove Restaurants Backend and Frontend","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/54"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"req-type-get-post","number":46,"title":"LD - RequestType Post and Get Operations","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/46"}]
