
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-07
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-remove-ucsbdates","number":34,"title":"Remove UCSBDates backend and frontend","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/34"},{"author":{"id":"U_kgDOCL-Znw","is_bot":false,"login":"divyagsubramonian","name":"Divya Subramonian"},"headRefName":"ds-rr-backend","number":33,"title":"ds - update recommendation request backend","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/33"}]
