
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-07
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"nw-add-deployment-links","number":60,"title":"NW - Add QA and Prod links to Readme","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/60"},{"author":{"id":"U_kgDOCL-Znw","is_bot":false,"login":"divyagsubramonian","name":"Divya Subramonian"},"headRefName":"ds-rr-controller","number":59,"title":"ds - updated rr controller and tests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/59"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-recommendation-requests-fixtures","number":56,"title":"Create fixtures for recommendation requests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/56"},{"author":{"id":"U_kgDOBo-IIw","is_bot":false,"login":"eug-wong","name":"Eugene Wong"},"headRefName":"ew-remove-restaurants","number":54,"title":"EW - Remove Restaurants Backend and Frontend","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/54"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"req-type-dropdown","number":53,"title":"LD - Create Request Type Dropdown Component","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/53"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"req-type-get-post","number":46,"title":"LD - RequestType Post and Get Operations","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/46"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"req-type-service","number":44,"title":"LD - RequestType Service and Exception","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/44"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"req-type-database","number":42,"title":"LD - RequestType Repository","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/42"},{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"nw-remove-ucsb-dining-commons","number":35,"title":"nw-remove-diningcommons","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/35"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-remove-ucsbdates","number":34,"title":"Remove UCSBDates backend and frontend","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-07/pull/34"}]
